Add donation information via Liberapay
geany/www.geany.org pull request #26
Opened 2020-10-31 10:11 UTC by eht16

Also remove the outdated PayPal logo and use a direct link to PayPal.

2020-10-31 10:14 UTC, eht16 commented
It looks like: 
![geany_org_donate_liberapay](https://user-images.githubusercontent.com/617017/97776630-9d505f80-1b61-11eb-82fb-09b6e10324b7.png)

I also changed the redirect for "https://www.geany.org/service/donate/" (used in Geany in the Help menu) to not directly point to PayPal but instead to the donate page on our website, so users can see all available options.

2020-11-01 09:07 UTC, dmaphy requested changes

2020-11-01 09:07 UTC, dmaphy commented on page_content/about/donate.md
> +There are different options to donate, including via bank transfer and Liberapay.
```suggestion
There are different options to donate, including bank transfer and Liberapay.
```

2020-11-01 09:07 UTC, dmaphy commented on page_content/about/donate.md
> +Bank transfer to the [Geany e.V.][8] account is the preferred way for donating money as the money is transferred directly without a third party involved and Liberapay/Paypal fees can be avoided.
```suggestion
Bank transfer to the [Geany e.V.][8] account is the preferred way for donating money as the money is transferred directly without a third party involved and additional fees can be avoided.
```

2020-11-01 14:10 UTC, eht16 commented
Thanks for the feedback, completely incoporated.
I will squash the commits before merge.

2020-11-07 09:36 UTC, merged